export interface RepoEntry {
  kind: string;
  name: string;
  url: string;
  note?: string;
  nsfw?: boolean;
}

export const repos: RepoEntry[] = [
  {"kind": "JAR", "name": "Kototoro Parsers", "url": "https://raw.githubusercontent.com/skepsun/kototoro-parsers/repo/index.min.json"},
  {"kind": "JAR", "name": "Redo Parsers", "url": "https://raw.githubusercontent.com/skepsun/k-parsers-r/repo/index.min.json"},
  {"kind": "JAR", "name": "UMA (Tsuki Parsers)", "url": "https://github.com/InvalidDavid/UMA", "note": "Loaded from the latest GitHub release; requires the Tsuki compatibility layer"},
  {"kind": "CLOUDSTREAM", "name": "CloudStream Providers", "url": "https://raw.githubusercontent.com/recloudstream/extensions/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Mega Repository", "url": "https://raw.githubusercontent.com/self-similarity/MegaRepo/builds/repo.json", "note": "CloudStream megarepo aggregator"},
  {"kind": "CLOUDSTREAM", "name": "Phisher Repo", "url": "https://raw.githubusercontent.com/phisher98/cloudstream-extensions-phisher/refs/heads/builds/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "CXXX", "url": "https://raw.githubusercontent.com/phisher98/CXXX/builds/CXXX.json", "note": "Maintained 18+ repository", "nsfw": true},
  {"kind": "CLOUDSTREAM", "name": "IndoStream Repo", "url": "https://raw.githubusercontent.com/TeKuma25/IndoStream/builds/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "CloudX Repository", "url": "https://raw.githubusercontent.com/Asm0d3usX/CloudX/builds/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "CakesTwix Providers Repository", "url": "https://codeberg.org/CakesTwix/cloudstream-extensions-uk/raw/branch/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Italian providers repository", "url": "https://raw.githubusercontent.com/Gian-Fr/ItalianProvider/builds/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "SkillShare-Repo", "url": "https://raw.githubusercontent.com/techtanic/SkillShare-Repo/builds/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "CSX (Hindi & English)", "url": "https://raw.githubusercontent.com/SaurabhKaperwan/CSX/builds/CS.json"},
  {"kind": "CLOUDSTREAM", "name": "CuxPlug", "url": "https://raw.githubusercontent.com/ycngmn/CuxPlug/refs/heads/main/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Turkish Providers Repository | @KekikAkademi", "url": "https://raw.githubusercontent.com/keyiflerolsun/Kekik-cloudstream/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "FStream (Repo: Francais)", "url": "https://git.disroot.org/ayza/FStream/raw/branch/main/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Luna712's CloudStream extension repository", "url": "https://raw.githubusercontent.com/Luna712/Luna712-CloudStream-Extensions/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "NetMirror", "url": "https://raw.githubusercontent.com/Sushan64/NetMirror-Extension/refs/heads/builds/Netflix.json"},
  {"kind": "CLOUDSTREAM", "name": "Redowan's BDIX repository", "url": "https://raw.githubusercontent.com/redowan99/Redowan-CloudStream/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "zzikozz", "url": "https://codeberg.org/zzikozz/frencharchive/raw/branch/Release/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Kraptor'un CloudStream Reposu | @kraptor123", "url": "https://raw.githubusercontent.com/Kraptor123/cs-kraptor/refs/heads/master/repo.json"},
  {"kind": "CLOUDSTREAM", "name": "Cs-GizliKeyif +18 | @kraptor123", "url": "https://raw.githubusercontent.com/Kraptor123/Cs-GizliKeyif/refs/heads/master/repo.json", "note": "Maintained 18+ repository", "nsfw": true},
  {"kind": "CLOUDSTREAM", "name": "doGior's Had Enough", "url": "https://raw.githubusercontent.com/doGior/doGiorsHadEnough/refs/heads/builds/repo.json"},
  {"kind": "MIHON", "name": "Keiyoushi", "url": "https://github.com/keiyoushi/extensions/raw/repo/index.pb"},
  {"kind": "MIHON", "name": "cursed", "url": "https://github.com/yuzono/cursed-manga-repo/raw/repo/index.pb"},
  {"kind": "MIHON", "name": "CopyManga Copy20", "url": "https://raw.githubusercontent.com/LittleSurvival/copymanga-copy20/repo/index.min.json", "note": "Chinese-site coverage"},
  {"kind": "ANIYOMI", "name": "Aniyomi Official", "url": "https://raw.githubusercontent.com/aniyomiorg/aniyomi-extensions/repo/index.min.json"},
  {"kind": "ANIYOMI", "name": "Yuzono Anime Repo", "url": "https://raw.githubusercontent.com/yuzono/anime-repo/repo/index.min.json"},
  {"kind": "IREADER", "name": "IReader Official", "url": "https://raw.githubusercontent.com/IReaderorg/IReader-extensions/repov2/index.min.json"},
  {"kind": "LNREADER", "name": "LNReader Official", "url": "https://raw.githubusercontent.com/LNReader/lnreader-plugins/plugins/v3.0.0/.dist/plugins.min.json"},
  {"kind": "LEGADO", "name": "XIU2 Yuedu", "url": "https://cdn.jsdmirror.com/gh/XIU2/Yuedu/shuyuan", "note": "Legado sources usually cannot expose reliable per-source versions"},
  {"kind": "TVBOX", "name": "Qiqi TVBox", "url": "http://z.qiqiv.cn/123.txt", "note": "TVBox lists usually cannot expose reliable per-source versions"},
  {"kind": "TVBOX", "name": "如意资源网", "url": "https://cj.rycjapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "光速影视资源网", "url": "https://api.guangsuapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "极速资源网", "url": "https://jszyapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "非凡资源网", "url": "http://api.ffzyapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，可能需要代理"},
  {"kind": "TVBOX", "name": "豪华资源网", "url": "https://hhzyapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "360 资源站", "url": "https://360zyzz.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "速播资源", "url": "https://subocj.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "ikun 资源网", "url": "https://ikunzyapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口；源站在部分网络下会重置连接，可能需要代理"},
  {"kind": "TVBOX", "name": "快车资源采集站", "url": "https://caiji.kuaichezy.org/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "电影天堂资源", "url": "http://caiji.dyttzyapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "魔都动漫资源", "url": "https://www.mdzyapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "影剧资源网", "url": "https://caiji.maotaizy.cc/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "黑料资源网", "url": "https://www.heiliaozyapi.com/api.php/provide/vod/at/seaxml/", "note": "苹果 CMS 采集接口，来自黑料资源网帮助中心"},
  {"kind": "TVBOX", "name": "红牛资源采集站", "url": "https://www.hongniuzy2.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "金鹰资源", "url": "https://jyzyapi.com/provide/vod/from/jinyingm3u8/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "新浪资源", "url": "https://api.xinlangapi.com/xinlangapi.php/provide/vod/at/xml", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "豆瓣资源", "url": "https://caiji.dbzy5.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "天涯资源", "url": "https://tyyszy.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "无尽资源", "url": "https://api.wujinapi.me/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "量子资源", "url": "https://cj.lziapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "索尼资源", "url": "https://suoniapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "暴风资源", "url": "https://bfzyapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "闪电资源", "url": "https://sdzyapi.com/api.php/provide/vod", "note": "苹果 CMS 采集接口，来自影视站长圈资源站列表"},
  {"kind": "TVBOX", "name": "奶香香资源站", "url": "https://naixxzy.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈采集端口列表"},
  {"kind": "TVBOX", "name": "奥斯卡资源", "url": "https://aosikazy.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈采集端口列表"},
  {"kind": "TVBOX", "name": "玉兔资源", "url": "https://apiyutu.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈采集端口列表"},
  {"kind": "TVBOX", "name": "虎牙资源", "url": "https://www.huyaapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈采集端口列表"},
  {"kind": "TVBOX", "name": "西瓜资源", "url": "https://caiji.xgzyapi.com/api.php/provide/vod/at/xml/", "note": "苹果 CMS 采集接口，来自影视站长圈采集端口列表"},
  {"kind": "TSUNDOKU", "name": "NovelSourcery (Tsundoku novels)", "url": "https://github.com/NovelSourcery/extensions/raw/repo/index.pb", "note": "Tsundoku novel extensions; protobuf index (index.pb)"},
]
